packageExtensions:
  express@*:
    peerDependencies:
      pug: "*"
  "@truffle/debugger@*":
    peerDependencies:
      babel-runtime: "*"
      fs-extra: "*"
  "@truffle/hdwallet-provider@*":
    peerDependencies:
      pify: "*"
  "@trufflesuite/eth-json-rpc-filters@*":
    peerDependencies:
      pify: "*"
  "@trufflesuite/web3-provider-engine@*":
    peerDependencies:
      pify: "*"
  original-require@*:
    peerDependencies:
      web3: "*"
  reselect-tree@*:
    peerDependencies:
      babel-runtime: "*"
  truffle@*:
    peerDependencies:
      babel-runtime: "*"
      fs-extra: "*"
      web3: "*"
  typeorm@*:
    peerDependencies:
      pg: "*"
  zustand@*:
    peerDependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
