packageExtensions:
  "truffle@*":
    peerDependencies:
      "babel-runtime": "*"
      "fs-extra": "*"
      web3: "*"

  "@trufflesuite/eth-json-rpc-filters@*":
    peerDependencies:
      pify: "*"

  "@trufflesuite/web3-provider-engine@*":
    peerDependencies:
      pify: "*"

  "@truffle/hdwallet-provider@*":
    peerDependencies:
      pify: "*"

  "@truffle/debugger@*":
    peerDependencies:
      "babel-runtime": "*"
      "fs-extra": "*"

  "original-require@*":
    peerDependencies:
      web3: "*"

  "reselect-tree@*":
    peerDependencies:
      "babel-runtime": "*"

  typeorm@*:
    peerDependencies:
      pg: "*"
      
  zustand@*:
    peerDependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
