packageExtensions:
  "truffle@*":
    peerDependencies:
      "babel-runtime": "*"
      "fs-extra": "*"
  "@truffle/debugger@*":
    peerDependencies:
      "babel-runtime": "*"
      "fs-extra": "*"
  "reselect-tree@*":
    peerDependencies:
      "babel-runtime": "*"
  typeorm@*:
    peerDependencies:
      pg: "*"
  zustand@*:
    peerDependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
