version: '3.8'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: 'redis:alpine'

  indexer:
    build: .
    command: yarn indexer serve
    environment:
      PG_HOST: postgres
      REDIS_URL: redis://redis:6379
      ETH_PROVIDER: $ETH_PROVIDER
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080

  api:
    build: .
    command: yarn api serve
    environment:
      PORT: 5000
      PG_HOST: postgres
      ETH_PROVIDER: $ETH_PROVIDER
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - indexer

volumes:
  postgres_data:
