version: "3.8"

services:
  indexer:
    build: .
    command: yarn indexer serve
    environment:
      REDIS_URL: $REDIS_URL
      RDS_HOSTNAME: $RDS_HOSTNAME
      RDS_PORT: $RDS_PORT
      RDS_DB_NAME: $RDS_DB_NAME
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
      SECRET: $SECRET
      ETH_PROVIDER: $ETH_PROVIDER

  api:
    build: .
    command: yarn api serve
    environment:
      PORT: ${PORT:-5000}
      RDS_HOSTNAME: $RDS_HOSTNAME
      RDS_PORT: $RDS_PORT
      RDS_DB_NAME: $RDS_DB_NAME
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
      SECRET: $SECRET
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRY: $JWT_EXPIRY
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      YOUTUBE_API_KEY: $YOUTUBE_API_KEY
      MAIL_FROM_NO_REPLY: $MAIL_FROM_NO_REPLY
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      PRIVATE_KEY: $PRIVATE_KEY
      PINATA_API_KEY: $PINATA_API_KEY
      PINATA_API_SECRET: $PINATA_API_SECRET
      S3_TOKEN_MEDIA_API_KEY: $S3_TOKEN_MEDIA_API_KEY
      S3_TOKEN_MEDIA_API_SECRET: $S3_TOKEN_MEDIA_API_SECRET
      S3_TOKEN_MEDIA_NAME: $S3_TOKEN_MEDIA_NAME
      S3_TOKEN_MEDIA_URL: $S3_TOKEN_MEDIA_URL
      ETH_PROVIDER: $ETH_PROVIDER
    ports:
      - 5000:5000
    depends_on:
      - indexer