export enum LoginError {
  INVALID_EMAIL = 'INVALID_EMAIL',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INVALID = 'PASSWORD_INVALID',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  CODE_INCORRECT = 'CODE_INCORRECT',
  CODE_EXPIRED = 'CODE_EXPIRED'
}
